# Generated by Django 4.2.3 on 2023-09-04 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_savings', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_savings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investments', models.DecimalField(decimal_places=2, max_digits=15)),
                ('goals', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinTrackerApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_savings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investments', models.DecimalField(decimal_places=2, max_digits=15)),
                ('goals', models.DecimalField(decimal_places=2, max_digits=15)),
                ('savings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinTrackerApp.savings')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinTrackerApp.user'),
        ),
    ]
